### ISSUE TITLE
train ucsd

### ISSUE THREAD

**Issue by DengMiao55** [aimagelab/novelty-detection#6]
Hi，thanks for your work。When I train it ,I get this error。

Traceback (most recent call last):
  File "train.py", line 201, in <module>
    main()
  File "train.py", line 192, in main
    train_ucsdped2()
  File "train.py", line 128, in train_ucsdped2
    x_r, z, z_dist = model(x)
  File "/home/dl/VSST/dm/novelty-detection-master/models/base.py", line 33, in __call__
    return super(BaseModule, self).__call__(*args, **kwargs)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/VSST/dm/novelty-detection-master/models/LSA_ucsd.py", line 189, in forward
    z = self.encoder(h)
  File "/home/dl/VSST/dm/novelty-detection-master/models/base.py", line 33, in __call__
    return super(BaseModule, self).__call__(*args, **kwargs)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/VSST/dm/novelty-detection-master/models/LSA_ucsd.py", line 62, in forward
    h = self.conv(h)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/dl/VSST/dm/novelty-detection-master/models/base.py", line 33, in __call__
    return super(BaseModule, self).__call__(*args, **kwargs)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/VSST/dm/novelty-detection-master/models/blocks_3d.py", line 133, in forward
    activation_fn=self._activation_fn
  File "/home/dl/VSST/dm/novelty-detection-master/models/blocks_3d.py", line 33, in residual_op
    ha = f1(ha)
  File "/home/dl/VSST/dm/novelty-detection-master/models/base.py", line 33, in __call__
    return super(BaseModule, self).__call__(*args, **kwargs)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/VSST/dm/novelty-detection-master/models/layers/mconv3d.py", line 29, in forward
    return super(MaskedConv3d, self).forward(x)
  File "/home/dl/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 421, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 5-dimensional input for 5-dimensional weight [8, 1, 3, 3, 3], but got input of size [105, 690, 1, 8, 32, 32] instead

**Comment by DavideA** [comment]
Hi,

I think you are not using the correct collate function in the `DataLoader`.
One quick way to patch this is to reshape the input tensor before feeding the network:
````
x_in = x_in.view(-1, *x_in.shape[2:])
````

Hope this helps,
D

**Comment by DengMiao55** [comment]
@DavideA thank you，it‘s useful。 but I can't  use the batch_size mentioned in the paper 。Do I need to use multiple GPUs？

**Comment by DavideA** [comment]
I used a single 12GB GPU.
I'd say you could reduce the batch size and give it a try.

D

**Comment by DengMiao55** [comment]
@DavideA    Hi，I try to recurring your result in cifar ，but I only get AUC 0.6. could you tell me more about the detail about training。 thanks

**Comment by liuem607** [comment]
Hi, I have a similar question regarding input size. If my dataloader works correctly, the input data size before patching as you mentioned is [1, 690, 1, 8, 32, 32]. If I understand correctly, this first 1 is batch_size, and 8 is 8 sequential frames, and 32*32 is resized frame shape. But what is 690?

Also, the original image size is 256*384, isn't 32*32 too small? 

Thank you in advance!

**Comment by ColaWithIce** [comment]
> @DavideA Hi，I try to recurring your result in cifar ，but I only get AUC 0.6. could you tell me more about the detail about training。 thanks

Hi, where did you get the training code?

**Comment by shen-yao** [comment]
> > @DavideA Hi，I try to recurring your result in cifar ，but I only get AUC 0.6. could you tell me more about the detail about training。 thanks
> 
> Hi, where did you get the training code?

Same question please

**Comment by BenedictGreen** [comment]
Thx for the great work! I got same question about the details about training. hoping for author uploading the training code.@DavideA
thanks again!
